global:
    smtp:
        host: some-smtp-server-hostname
        port: 25
        user:
        password:
        disable_tls: true
        from_email: no-reply@example.com
        from_name: MailBear
    http:
        address: ":1234"
    

forms:
    some-form-name:
        form_key: some-random-key
        form_cors: "*"
        to_email: recepient@example.com