version: "3"
services:
  mailbear:
    container_name: mailbear
    image: denbeke/mailbear
    # build: .
    ports:
      - "1234:1234"
      # - "9090:9090" # for prometheus metrics
    volumes: 
      - ./config.yml:/mailbear/config.yml